services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-dev
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DB: fraude_pagos
    ports:
      - "8123:8123"   # HTTP (clickhouse-connect)
      - "9000:9000"   # nativo (clickhouse-driver / clickhouse-client)
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: unless-stopped

volumes:
  clickhouse_data:
